apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCUtkKz2t7SI0VKrpc3MzzlU3/B8opqB4gzJByJ5Mx1GAlHqWLNjQLAyg0KGTPJP37jCDCzxuITKpM2yjk7vbqnlNgITFcF6ggdL1QMfXDMUdIG3nK0X1xv9+cSfXWTLO1T9G/z4C7nNtNsahfhrFq2kMw3GNFdDUDrlPg/QtDBU+W2UxXhmxgblRy4GimGK3/p8dEox5wlf6HmZf2dYp7XA5RkAZNunKzox8mpvh1DabJVgsCD9B0JgXJBKFSbJSk+qAKb3UAcobob8GQ+UG/0w1kPuJdjVxBH6lBvfv3tz8THPA1ecAREow3XXzt+RtuLp4pOaHW5qqPWd/xl7DHZDvM6o6lnHxvt0VKE07J6SZnuVKh9UFhguXumWc0FCtK/beo/RHDRa3zavl4sliK/g4tOBpFogq539Yg6lTdREli4l0iqV86dUyVGL5ZNGGXe8SE53c/cTgHqHpVypc17ybFz6zThPqjFJrEzYpDlOjTxmBKq9iue5jYTkQsVXpQ31YxM4ZHmH9Upr9g4y3i4Azq75ruzWHmIfPSaE/SEWZ+B5b/x7e10ltl8u+m3pFW02FpB8W948sccTgrZbOfewur0aDsbBENGoxQyQigTWE9qHjtoAztne3p1KeNzNbMfK5O2ioHJzb+qkn9KRScg7duOOL4cccjcUBO0iAUpHGISW+8PloMrrzH4mBnZzULhYC1MR+CZbtYZOXBteJgfUJj/4B9983JvoLou8pyTmN3kLgUOdNP8Ha95v+pFziD0WwZg1AOQXwMu+aJsLuRWxBSBqwJLPG3H3GZIDUIHPS51vTV04s+/Y9n5vtopSgU10xfjDVWbxdFvPUl1WZycCmL/kJWJCPEIrJuSrWSmp8MY33kMdqLnxbecQ2oBLhlPUdF1Hx/p
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

