apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAjn9yo0YIFfAPtdGL15OJnqlRKtV+R6lv0Zlvj4+MsIUPmvjAodJyGLKMLq1GWtb3M/hf/pewBCHz3i368/RtjKkd9mANSPfjHZwsxgkgw67oVfyfall4j+j1chc5oHi+62z1umkpBIckUboyZ2LHSWmiyismrvbdG8BeJwbYDD9xyH7XkkO+OpHBx0yWAQrFhmowQNCc7+K7uc3E4Z+B5+LJzKqj4jdKPnSvEFxfA9iE4Szfd2rEgwpPcWC+pvtUuAH9wvCDD1SeHPEgXSSHmW77jwE0rxV8DJcN85lPKboHR9xjSvs2w6DW9oKR/xZ518iYlGxQ0DcFA1abveLaGQdzHTsF5vANkAdNOBfdb4YDfrrAkTfFlv7swnB6lK41zgH7aZJOEPzjBe2hiZnLHr7qHxMUf+PTSE9oncGI4fuT96SNo0hqMrsI2EggVrT0AopQaROv5/sTi1z2Fh6bBqFcWRZUmOLClq2cGtBSWeXgabCHwZgur8USawjoqhAPD10jaax+r6mbL7Edrzv4Ny6aNvEPvaioktQPNaDm8j88cYlfZSiFXuYXN/ja5V4+IXpngIssGzez+yslHFsLog+sXzoNgPgACaqUhNdS7D+ukg7JU2mweedFy9izX9fadoGy9xUFHbDDWO4Vp1vue2thGHphG3A6NGTLP2CvfELEc+O3wONkNQ6vYlbE6HP6AL+1hJt7QqL/W9/U7MWsc9QrAy8eu6pOy2AUwNVsvtQOiEkHvK4u2MPmw147khUmU5sMkpJFi4DhGICcVO1yt3mP6oJZK1fbMO/9GRQEHLFxSnAT50TPKwkW+AIB2pDFKYldsUAr6PxWJY3Xwctnt4oA5gK6M9TkrCT6Fz85JXZEdz2uzQTHrRo1v7j/3G+f1HfVbwuTR
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

