apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCpaRgpJS2YfFg66codcsiAEssUoMCEWzarM3KS1pmkeNqxwOBdWiSTyL9lXujxySCh96zlSlES/Ha+UFpTJLTy8Mw+XuOrklANLV1lPcXmxwNIJqFSTXv9XtNkZrCsYMBQ0iWSyWoLdncdOj7ydbzH68jVL16gJJTW/21XRyzj1yIHrFQtlEnG51jwnKUkX8ECKgyjt3Tp9y9CXR/rBfwy6UuIkb97zL6m93JNfEmRMEU9uwnG1rS5axvz5d29Zru+tA9K1J9/wd+1e+QbQpKAuBNcfZyoJNweRqUhDXV9eDWwF3+B5yYjC7T6uAUn5XKXpiBVIzKpmMw8gxoWgx9FCsBPMZBHbjv8wMpBG1swUgABBkpa9XCZf62F7Q4oSslbGaAfhkZ+o69gnhbLBNUnoiQtNIebb2XVKoRY25UKcHEMdpMijo1xlWt0FyxiNv2y09tp8YA2QmWPWlCk+nmSItPr6s8MVk9a3VpeohInAWDgM+4BVyxHjfFRV/ow2VZP3rA+1DCzQK7srhV3DXaX3FO47DSwJc1rOtXV8f3s3LObrg87vnf7US6EzYMkaSuUX1btDzwYfEOclH20dy7PYA4LjNpqpG5ocygze9xcafGy9dKHcpVF4v/q4tCOsuNYOcWb3tEEpjFB79DwcV6axoE19QZCNArTj5/nsq0T8bEUvc8Vf0tnx5D80NLtKO00ewVY6PwHIZwQvJC9+1pIASUz7sJATnMwcgT9+cIrlldVkn6ZpGpJvF4Rz8XLNqBAYAFK+b0dg1YuEXgAne5MSbZtHsde6RTEkg7HVkQW2tziI/VT3SmV/PhCIldVS6MskFO+GzELzFmw3u0eDuzthB377nt8R1dT+zabORHWxd4fD0bBfqm6DDQgbn9dPXx7v28vhrox
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

