apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgA2z2pgq4Mln5Wbag/7QxY+6hvvRZauaHbeU9AcVxFpCH9FKAL2Cg9L8GjNxTlhasIJS6bQ3vOfW/xDJ2zD9jxVxLMDCHIxb7G4DCs0zSy4nJiReBWt7w3ys3D8cNPDi6w7kfD+8VDb2EEWeQKiocUexG0vbphv8EOBTrWO5v/qIhKFsmfVqrr3/r3D5Ccnh82AMXxCCSnVBii3UO9JmuEMHdvq7fDvSNPCDSHk1I9/T0aQxInhW7DUj/7kmu+oUntmpq7XYXQmWtskt0e4Ksd6Jibje2eVOa3+QWWKFyJ//hBgC/5LFTDeuDAwjelIBta7u19InaRCzCOpMTX33/r1i0e7AC/4GpREzKcYkYqKAiXROTtt751/YFjoNHE3CCme3RJXFaoX2yxHZ0NM8STXkjcwo/1bdfyeFGiCnW8qYYjLvbSCDSqyesp2WXQP5M/n8qoA5MCNBiOIx76Yf3UfgMW+hdUnSonGCFzK5jmtQ5oHGK1JKvPpTMIyJLe6xubA6EMy4NBj3loOpeS2wUso1/NqB7VRvqwSuyxYA3Qhdkklz0o4+MCfnj4EgIhuKWBeI93qYAmleJ4s+mUj/NYwpy18sF+MFo5siuco51RMW4/bvbnLYRySdihO0KLgkbHNnCbgUNUTdOfIIgfvbptPOVxagj/OGE3+8SCWCbGe5AhSpvmGXaX+0VBHdrnOXOD5pQY9lEQ4Uz26HKFdx+oApsVAoxWPmGoLYJfCX89PiIWtJWGjzvP2f/psAZrAW36UuuveSzjl4JNJL+wPOmSHodGjrXJq4UXv+3gqRDzx/3rkiADtZkR3Tw1dAD07GOGuf6e9W02vaJHRetYDt2G6ZjlyLCTuNtJWCwWQfYgTbegYc8xh34062MNixEOpabX/BtKcC8Ho
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

