apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBjmXesXQ4nwdFszs/w9WvIXKdjaAfqyBItHM3WvVIw264Z06cEMDcp/6Y5P7W7iCGEtwnBJ0hWs0d9clpuZCAg1nTO0icf9iTZfcOxpSMJmhcnT0HtiuHWcDq2cD3QxEkss51gQHNlIJuiMKgKk1ftFksy3OsGT51ffnPn8E3EqVuK2Lr/ZRdhiYgozX74ZaFxVitt/eOw8or3NcKmYxWetjsGHFwXzX3/ZyeeOhhJuNboiktiuo96d1OU+tEcZPdI8oDL1iqqyM1Py/gtdqxVSrFTS7I5P7LQMLBstWd2eh5AQriqUqK+5S4kiMmUnOuM6BPO2t/cL/aor8KiEosMw/EaNgddtQGyCGdnBPT+LZWLdnaROiIzu9jFmIp4O7QgT9C8z6vSBfrX+/gEKPuxvQLSpOVanowMh78+bRoUOSaznZ0WZ80ewnC66szxvRDfyu07OhGuwre3XipOK5e+XBn6+DhoimHO4lh8mEvFOICYa1LzPlYSusAi/cQYnf8qqVPWEybf1NF6OsOYP5cUkROHkoAkm/HilnAcvMI1EMW98eylefu63bQVGODQiK3JulTeOJx8Dc2t7KOvL0LUk9TSmcEfJs+4Z84LOBMiqabAfR0OGYeP5GzfABTWnOD9USPi7cX+2sMofnvivxdBNaVN18HPGc3g3g7Om0CzuSm+WSCNNu1EWG6/maANkS15ATF7/aVs7Jh3unyoAh6uvKQrddATDauQJc7SuFaoM9+vcU0jWPK1tPK3d7pre2RY0wDETJ6kWlbAL+WPCOzasyH8H2r+pJ7wxYoPG+At4l/SuAxwtWU1BkSW7F3FKzjS8W2O3+XDLu+0DERbEo89q8lB4FXLXsh/zTs1ExH+AALulXiypk06Cx7D0C7y0yz35b7Fh0wl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

