apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBsjs4/eVg17qwNDyjPoykziIa4tvPHwF+dPqPq1C4CLk1DauXR/PJ3CbywzvObPhnJc1EaqyzF6UN00Jirf1Vme51ntmRJcp5RkLRMcNk+0dDn1L1yuZbzQCF7Vu27fw3QvSAbQP+HGNqv48E1aDsxh044YzKaiS6yvvjJRTY6jw8kwPupeLKSwlRA9vvUub17Y/mPmmTYRCVyueiYWGfCI5tlMKSKLnVN0Zth75v0U3pmw6dlI822aAqeiTCFbTMwCatK/W7fZeLK3Q1Y+g8rgHBCSflBdzfgODRRr6oEMgM8Geuz6DWJ10mq1tXZZojBycNJ5YDp6s1gbK25XBb3Va+Prppj1LffmKG4BxwmOC3ZZ89DKgPqHDrevaFjjwisebP2tncBboblWIB6rx03SzBaajV37kIqUTAaYjR89i8AY6tACCQpg6GnWLfrjRCKX7xdxQ/MVjBBnZSbOwKktYrlhrJNFMUb38+Se9CR+3YyLyR/1I1R7oMu4oVolxyq9ZhbsgTZSj1UnPpujb/tQW8uWddXvf/DGhI2gSRwqrOTDWFkLPNAyA2oLFInYTbBnOh0sMTB8MQ5wkOpJY3T5OJ7b7BJTOSKuP8aAchcLCNCjDbeqor6p1SFBGEUfVxRV4TIIBmjPlWzRvCR/3+20v5ExBee8fgszZk8SYsnDVTAQvzJE82/UNUD6SRHUebgkXaPlz3pvYwGPku2+w3FYwDSf9OBpbtXkyt8bEx4p8xwYMR9qUH6fv5US+zd7XUGY3ZvJLvYEkzOgVitLcVWjn0Ow30H22pihMsn8Nk0fo4ixKBJO7mNPG6GXxXU4dO+9ebFehxR8F3dpfvTRvuJ+9tSDUh7HvK8gMSUDH6SvJxRizjGbYQy31MTh1Je4ZTAzKTcBRbC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

