apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgA2Ooj4KpHi2bIYVh/IpgtxqvbcfuDv857HpWOLzFcY6GTapY/bLGGAlT4xFpuo2YqcKAG98SIdvkK7NUQuArO3y925EqsEZEkqQXzchq7Ja9KVfPCXqAbC2ZKF32tbTEMHnE3Qhgon1ib4zZB7IDazgyV95R9GOSvUYyqNYqlrD9CMH0hOJKqThul4Z+FiOkmKnp4ua1eTZfqce98Chhu/GFGXZUidBTPfqECF6szH4burNFCprtPilWpoWn24bxRJNHwCdok1Pfl3oeG5qoJmH/+C/9R4b/RNucTjc1iUH/VWIufLRSBqxfxKfUHy1HZ9yhlSWtx2liBEvhbYO8n0iPwSYzU1TKVY+dOXtRjv3mGwIAqP6TWWyV6fKR75LnA3hItG1+hJI/D08BIjEhfyMhyX0tsjEzJ6JoHASvqWjmBTzvxRLJqozLu6RcuEGGBFwkV8TbSzwmWYZbnD8N4cEOiFqJO3II7ZsqQDFiClD3bYRoPMWNxT+zhl4qHwgYOErQXd49OqLL4vw6U1PT9SyVeGDx7fszlY8ffkgUSV0IxCvfWmwJKATtlGzS2t4JWStsDPTInwEwmmayYNBbWew6muGmzgzCcAfBl0U/P9pAleoDFr2tjaQDko5A/a0EEpkQiqAij5+pE9cvZuSUr683TCo+PYynFADa73R9KNKNVTlgIQWP21JXX4uRWuLl713SpPm7BxNuKkjDOecUsQdMjWKv7ELjk+q7stWma0cZ802X7eSwHwDrhXjoNk8dtxt12xL/ZVil644C5ZtkJ39coQQvoDGJAZp12d0ljNvLd6+44/THV3gun+EL8uxu0WJ5CR8rrdNGKWNkY0XTteJXoaQUXx/e5CmW7A42QtZNxKuOp/d/Czsq3MyopZzTqMVenLZPXN
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

