apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAtpRL/bJFutzUXFCPrgOm/fjM52vThp1hVgGw7Tme3aaiBNsfQZCgyfKfLXJ8Nw0slRoYY17Mu6VzQfYbGsDcwxzAT/lpLvrfNfFHVNaFItP1KLwlLoTQjTPYcmJvHEA3C2TZ2R4HVfQWzr1G4R/r+ju/JOVTkXgYNVMO5InUPY86S3ybzUMM3yoXfRPu9tJ+4YFcHcPkwCvU2Q7wkY0Od3VuO/A/snrQs//P2ZhMXOTVZym4ELZDm4tsl/u1OlDzISqVRYkrPKrAIpEJWjHqloN0MEiRZlkJVHojliEcyFxM34JQ/mDwLSyU9nX1xn7VO4Hi3its0vJH8VFySHO0y/A8foE3skNOdeE3850XIUQY/SpF81ziARqs+xdwnMKYWNeSep62jxLI4Ne0X8KdkLTYjwEg42NuWtRJ4g8CNRvpo+TK+l1dmQrW9klL82row18aCVIqrFl/vPMEED9nSKYFZUgRB85VbKK8LfbGg9GoGwQeTTwfm19QnmjrMBthPnRzrhqZ0ceaqtDdPlDv8mcd3N8qBDHmG0/5vKaMd4cXxhhY03AVk6jPiFcI/P97BDOrpS2L6szeqFe2OnbElXkW62iKSTVBIX4Yf35yp59e44WAnykkQx3TMu3HlqADT3GhfuZZASf1Is+yF02dqNvLg2Vh1G+SPR8qjNrar+GTqCIlM96YnlcIUYizcKbZg8WXOd/aN+S4qN1F7zaPazf7D74ASV4Uh5cLYkdbAspm46pk3FbPOaA7kgToe1pdK5QoTs8ppjKS+wP0qJQjb8E5k2yakQbrZ6D/6SPXejO1K2CaxHDHp6xVQTfgy1FAPPqPo+7pRz5T/DLvdqbidlT/4HG+O6RZC2Utb/8wQysZXnjvK1CJykAiaU73SLv7T4jZ2ftOB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

