apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBgbBc9FQOFKoK6nk3jh6Icsx2NkgirRIXKo1QgfIB6bWCTd4i2mICp8/J4KMODOS++mp5PS2yr72oR/V3d7VwY30Ut1LkbUspX52RhHSBSbIWSsh/ZONCPkR2+Mfg/BuCsSBZmJ1OvjV7tRnJbn+heagiP2EsLoDZIs427cVssM9l+FamUfaj1j6eKsTrmb+6TKE++RIl/39Jyzbbx5bCMJP+VubPeChjhXO0LjSCcqzC8a7tj4P8CLA2H7fEGti88oTBL/w2JKy7z5z5oErBOLA92RWkZCs0OCYQMTOuee17zHUn60ZjEgADfE2xeY6Xsr+5uB6dhasXygFmizhBT3eNK1XFP/YtLcndL5ayeyC9qk8atlC2XVp4F3+wwTzejbVPis9bbuatN1JEYApNc/X1Jg0sIhmZkj7qfhggtCMWm0hiY+BDD/elD+UupNbRlYLZ7KvwqWIwTE96MUzekOWmQWAeJ6k1agwrzQtlQOk6fkYVbcFS7XGn5kesSA2hFCSODOD8X1aApVnIKXaVAc5H87sJNMIS/ujTNy8G1sXgiTwBIDdUY6Nk/BnWKRhqacivZaLgm+QV+PU4T2PAi/uNsbZO0QXfIYKN57w9f+puup4Imleg57WISNGGWPuWzqMhH1dNE5hV1CY3I659el92QW/1GRlvLRYSjfdNJf2SrMEqo/wofLr1a9a47pzYbo90k+ClcOzbhMmjdKgtSGflVl9p/gQiREY39D75yOOXKrbZKAIxlzMGOFQco3I47z1O5sz10Hfmfy4eHBGafKLSzOLjfmUsXY+05akpjF+rLvfYWQfvMrJJ5mNADchSwyPoNMlNWup/79TWqy443e/+rTSDct9l1r+v80Yc+9HQfF+jGtbmrtzCX5V0G93cEbVaYX+Jo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

