apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgC8yCjhdzrK30vkVqPBWKrg/BFQvF/YC4HrIravaGzice+UoH5N7gZgYVYY/fEKG7QhrVH+uYd7Ar4fWV/twE9WkUsuJ8Sq9TS14XFRwY00cXEWDbn6qwqYIGK6UO3nel3+2KtwSxc1pIXD4ldZAI273T85B+YJsGJGLwjJlFh5FPM2hcSN/H0iLWwbv7srayj1gG3ptULt8cs3d4P42MCC8lliSaxGOMfXqr4GUdWSxi7Yy09B3fhiqwBS16X17BZ3Oheyben0KwTfib7bdkVt7IdAjsqLHFIBGyoJN4dNKEAJGzbM8TWw+5BuifmVgWwQazRKbuuxzrf0EOUjEr6eSEZ9rtm4hiDKITUFQ+mjTzJTKASdQpNNsGWXU/kgcw0ILIstDe4pLRls32rl3DeKN9s70m3TApK6XpFThlEbQCz0F5P+zxwhncBVT1papMkCft/ijOvVnygWnll95+BcXGW5ohISfFDt5aMEeYq51NaDQun+HxgUE5LnJfp9PLDgEivfIU6rfC2sRheHly5XqMiYsxM6EbuPfytSNrq94J61QKtKiEXAQcp8OlmgK5+e1OZ6wdEDQzwLOQ4RuD3zwakgJ4VFPDeNiLh/UZ0U/YoHcdl9e5XvCW0py3cxYcMbFbq3f3SqcBLsilrLezk6ef8PMGQJlf18E/5LfdLkuaOipBaUH0vDRRZwp9+Y8SfF91fb/51TNkTihl+k978QhLo3PeD+vwzmAiopVwQhUWZa7cdHH48OjmOfEnb+uipt/T2lq6I+lfX2UKQ0xYtQz/BvfhV8WNFzlyWPLyf9exgEe7xNMLIKDOjPiJR2PxsvOLEog4ZdbqJjgvt/05HooP9vSE+o1M2u6i7wh/qGtoltusnTO/yZNiSlfILCUHFCqNyNYbQx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

