apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAe4OyoZ2/EE4f/Gczq09Bmh7CLbqQyoOc+MSRoDjDOInZiYbj4zeHyD5q43nHpTjJEK4w5a2y7dMfsNO492Ly1O+/GQ4G0pKPEKhJ4MMecm76klXeqTPY5PT+t1L2+0RRNq3pwO+SsxrcOGvUI0ajAGbjMQhZAnVc0BCbE0Z2+YeR6K2kRQjXEqQMum23MOy2lO0Q5fXzCaKqn8OpRWYknqQ2Pml2xcL7V8uF2QPU358Tr6mVsgTqHhH+n5K2Wji5xmivYWpM6HQEy97fgJ5a2jrvMSXDnSAYlfu6L8SrQUtx1GYbnT1xHyIB+82jBdSK+kOgiHSLUdRL2Ga49hossECr9HPiC3lqoO0tw5yZYB7INGQb0IbaZd4iCAqiaF7GMW/HFV5dbkn+c+bnqGNw/4Y9JxX16aoiGKiTHHL7Kt7npvRe/w9xKgAkF3KHXhKchxDFkEphluENh4/TBBpwpoR+VGCe974UjvGm4qufZRJLuPM6/WETVdqdsiAoL3G+L/nCURHAe2HqOHlC/1hpNrODyLPbzEGFXd3yeGAtcp0k5D1Zk06/kfpJVXd+NdjFvaLtvZSFzTnHT2mWLtpu38RosezfEGn+CyKPLCd+MANaBJmdtYjhOyx1qWQSfZyRiegtKEZvStBKmpT1BVt3eQiYvP4QJ31lf39/oz4i0JLDh2rSMcy2cDgNQAgLfXxr7VZ0EfpfpbuOOAOUiAR9Dj1CeZRADsfQdf/iV9OdKabp5XrofEYPbCUCd0xuonCfEKJ2dCH77ZBje7PwYov/nFKsREWYKTlQUEGG5pkIp+QL7BOlW+kfhT59eihF21Ry9lRnWiIOQTgkawu/cjBamN/USav3hAR9MqSKE/jv/Tcqpkz1gprgEUtI3kHmV5WAzdseRr6on
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

