apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/ellya-org/argo-combined-app
    targetRevision: HEAD
    kustomize:
      images:
      - dctellya/argo-combined-app:a926e295556e961234560470231f3a25e88101ea
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true