apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: argocd-cm
  behavior: merge
  namespace: argocd
  literals:
    - accounts.workflowsa="apiKey, login"
namespace: argocd
