apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/ellya-org/argo-combined-app
    targetRevision: HEAD
    kustomize:
      images:
      - dctellya/argo-combined-app:813040d3d44c1a85505cb15e5807101008c00069
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true