apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDMYlUhhK4FypLBmW1QIuqA+7TEA/S1PfjZPsOKfoM8LxiR3QSZrDVdff+rBVnL5OLtX8JsoEFrdCfsE0/ng6kt4oWDgLpLAmIwKDALgB4rOd/rXAlUETltiSHaTUhyBUpRewNZOYAzfRd45dlj8T7hqL8Z9IPA8hTMZXzhUEciryD9hOc3EoHz7DvCOcd3f9zq4aLPrpzPIR7a0MOzZTyRi22SGayR50LJoH4GTEB43iGzJmNbfgx41w4l0PyAlyZGgFVDjaJxfVdnKJ+C0Ja+PKdkrYR33Tr4/YnB6zN2unfiJ7p4mDCn95ObXX5DnXSTFpQHVjTouplx+B24jmP2dFA7Kd/6YWi7K5VUc52meZloBnBBUW6watYuwrwJZaYe5W31UiYIjZS7Aoi4kUEgJNMxL2k9v49l/F2Y0hQ3qsDp9laG1YSUIVCCpjYiCfoTFkJbuwc+WlPAKlKAfQ1F5TLAHUY42YSPiF9Ai1w8096l1Cq+80K7R7SPUT61RYRz0oU2hgnWX+ojIOwd/fiRYywHrL+bSSzXoT5NGM3eqC/c3WM8dbDzZDyEqdVUOOCkhb5nS/vi7V1KT47HUq5FBTIuV4zSqmkYWYGifWQub5ravaNLlnTHVRyro4x9s6pwf4Ge6NZnCCXQrNtDEabb7g2pO67fOUA5Ukf2nM2p0B0OgOmASXMeAsuYjQ20O2osJwPIhD7ZcPS4OpZsIKl3X9gqCuDzRWTEVnhfQXWZe5ffN3w4cOtx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

