apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgC4VeQvSt0gsdbXCCbMrh+gLP/PTj+SzXSSQePlfsljKrBBo/BAc8/iYpU/iauTd9lptUHGLZ7HDQOJzTeLZHfcJ/diCnvUjqMWEfxGPlsIUjECc/+Cn5AOuTbEJY9Szmgl5Ph+AzU7rHI8UcRND/B7clp3eUHO2AzeyZ9sFfttByJIc/j+chqc7WqJeIFiJR1hDgZLz0rA5ROkNtY3UQPNxYTwJqLWYNFyh0bkmcuGaWPkq4+FNi5lYwTAqvNQIb5NhGZIjRo4ak2oJ2X2A8U8oHlhkQruJk0fEo7dN/VSwlFO7TW5ZrNtlnmVX1vfkhbP0w9nC5Iv+VoO5qRofC9FarXYk9geU4jRPoDZoiksnEvtUla1PFeVB/KA3JTqRfvuydDBqbhz1hfffUo/wOvEB5wQDTB4dKukWO2PHcHbKr0Qs1i2zr+EE8DJ165VMM75+EHYbbUWpwU14WvJYM0pINz0V1ZZoXblo9VqMm7Z1kdATqCkzlt0HLfE0sGo0uqjj1WWbdRaNwU9MvtAvEXYmZvMPiB2sQMGH75HHZJG9/AFp+UEgUZEjKghX5Qxcs/NArrdCa7Jx4DjA2RAat8GqefcHHaNqvwQVk1TFn6datGC6FL/kGy1uaLWbDj1ytZ7IlFt/Gz2OZvIBHkqPOJflai6QRil4DO8kBZmn4zXOezL3Pg+HaWfo4yZk2En2dnw7UlK87KugMoVP8DT6igv758EdtPVdvx7nZFnz4YEGu92OrX5fxfc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

