apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBOxMxFTb4skSqa9DfM8o6s7mQDiNUsHZaJV7Zzps4xvyjDIw41ht2dCDJgLWAicc5JsZ2OEAnItIrMjq6jtWxSyVH5+OEfM/GLR6jQmdWDkgePXoMr1jZ340EwcC4u4vmvN1nCb0LeXsoGDmVE04sWb9Pk0NPIAwjf3CaIJSEKehwbilYa93q/uxBS/UKRWmAny1hJSvJmKWeu+7AOrld+1oj8mzNfqvtwZ4xzMXDuH/vGUiW6lnHRP8lGzaZDYfKlrvts8DVxDCtv3WwLdo9TJ69048oAgAtjwdPb5J++l6M+TGRCEQkRpg6UH22FKMlvfTIe+blT5+rZiMJjBYlg1NhcJ65bnZQNgQL82js4PHrd5upe54kHp17ahHzxFDXbo7/Ylx4VT6WAt+Yiu5GDa4hWCXrtzfxovIgEHJieVGr9gLKP3V/bSpw5lbqkOf/bvKqjyZZ1c1G8W1CgnIy1aBN4fJxLzRNJZUT1nx6my0dOC2I9mu6A81jvVwZ9E2udv8ZjUAzil3UnFLWKdcVXltgpB5kI1vX1Ir3icykKRedRKpwu+oE3huWGNmVh8lIoBQ56Lofj3qkfWQ3pi+aocqQjs8AU6UoqNCTXFdV48+NRYKi3D0z/8Z/oGfZZTyGn3iCRyHq+z6yhS3W3lSmpaS3w86i2f+oFz/tapH3Uw/kFoQ4pfHKGPxjhS13hSAhzo3YcNQPyo6wPHV81Dtid7hC3lZ98YBjS+RQLWdpjATjR1kx19BVw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

