apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgChn5s39siRRDT/qtXKYkrnNICg57uVKxfni993C3r8WfkUxbBHV1AOpDoDchPO+qsLySrYfVzxDYjVqRCYzISDBA0K4Kr5oYI1dRaSiREBymQYhI+gn5Ogv5DkmuJK0DdfTvENmyG1gerOGTM/erGIxXxZ5R6/4smGFQptM9krZPq2qjSAA2c/Dimnq9YjrjwP7uQX9iU736UPGcDOhXwrHYCZ6EOnkq+nHv/ZMI/a1VJXPumugJk67XbeP35sLRc5PyRKITtbl/w4+InpPYJedQTnoueZNd+h/ecypgytcDSUpeFdH59qXR+43H2ld2mrj6Nq/C7nJE5FfT+xaqfMZzk7JENPj2aVp5Px0anIY3MD+kN+89wEjNzmWxb1G+WSPu5quLmec2Y2Y7d25+ganu++Kjbs1l36aI9l0FlVg5MrQuzUZrcegkaYhZpSGW5QuJ++5zWAv8s7qH0ervmqrjtVagaEeAuAgehM9bGBbtww5chMpjHwWCw16RGjmR3ovWlGG8feQjhXHVFwmJHOYaMiXc5I6XamkykEHiRR13JFaJf2pJbcJZMrKqiopKDG0BF1VmQQYMJPagh7vAGGA35uyzMlbJodjIj/kbuNws0x1fzIqV2GTCnd0OsM2C+emdhNy+iJ0u/jxe74rNRnpsR+9SN6+JPm7hVvouIg9MU7GvBSGzeQHHZugDRFXq86cjVWkZzPv1clBvaRUW5J6w0q80pnt71FKfM84VPKYg6Cgpv1cpyD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

