apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCbg+j9HzLJ4zGo2yvpCvYbhHd8cym4sNEJOK4qVWoNMdaxJ++KTksyo/vsBG94tZqg2eq3XNE2mvKLIv9r27gOwRaHUR70F6/ClON5VCUz7OWnwDZGWrbOO0UeRUgkdxchTCp+qmrDAoydmkVM2E0uokj4BUKX8L5ABphJTx5JJXh8h+nuANLJMWgXa0IpKQwlR2kPjviYB78AM2LdC6nzqkjqe5WbsfSuQs5zb0aPCWkGhlOBmoYB2AiCUyDvacNF7o91ukI+fpAodOMS3yvm3eB6kzJDGwPOXfHkSjdFXEDRZGJsmlfHZqJxafs7oI61ZzNSSeKmOGdcVLJd15bXEdGt3g+kOwMa71gb8/7aKZT5t4K+G2qDHOX36Ch04VyyGUMbpV8/xnn473cfICUZzotdVGicFTxFm12hS4zYZWP6obqjdKlq8BCrlNploq9fbVwtwYNeQJ4noETKBqrZripq0tdLMk0hDKCg4vXtBs0dUadZOR7Ncfcq+oj39cpJp49C5ooIvtJ1NX9VNtw7j7E6FQQ9a3zDbNfLU+X528Ef1tb8Ju9xIz+DKkUaUYKfTpXWOhHWB30svMBiFxB5PI7PES0GR0sxvy3Sd4DA2yDV35YCRKK20p5zvlxRqAUE4gvAAtmRdqxNGPbeYEv+EKsqq7OI/DR0i4FktfWnfp9p+OC5MVxk6IYj5/jGzeLWG3uM0w5dgq5qdqkzqm6GtDiZSP1MZxm30DkaL3xEEWsKTbjnaPgQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

