apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBkZhQKQHcLeJmPIRX9QIQ2XAohWqLvtMyc1G2BGvJ3i8Rj2n0WUoTY8uMrPe6vhfX740+4oKUtzop+4YN9WB2mBO/uW0i3j61NgMcuwRV/liC6DEmSst0ZQ516iLUBAVHSEcay1NppaIeAY+lwHL81uIDNmwkzmHICukRtU44KkaSxI2850ClAAJdFVoPwZ0DQgT83GWnkspB2HsaUqlbStt3CfM6lF+/v4fJCck9msSUYR6AG6Ivw8b5ZD2beZsQcLk12lGbeO6UAWjR5mMskpZN3Svu4xZ1Kom4H3zsBynpR/m6Nh7VF5zvtEeCA+6u/oWuaG8nvjircPBXoOtJ2W0NgjLRcVXwOQORzG2ZdJFYU3BOESKtGXtrX3OI1ykDYxBItbk/hmLI4/RYn5xw+UkNdVeH1zFwzA5XNxnoLyKzzOnDVxl3v/M+hwSIuDNSmv9yaZsVY0ZJco7/vhXV/W9mLJv5T6rf6uPpbTpSipedDD2pC4dXPUbQoMNZSCdi/STbcQ+A8TmQe8/jFyhTZU4GyczFSUt6/leX+hkgBnYa/HRuAHQORktxfHzaFKMpvVKK7ZkMC+Y3/Bqmnp7LWdJIRf6a67c5LjRCFB6O6KHjBs+nCPDIggI1Vvt89w+szMBQpoYy0H3/hC3nbyHhRkDLbZqc9z3DDPaPvjOzu67tRjZ9EOm6QrWNtMX9K5d4/TpfxAk6zpXjrCgKMZ4c/jiPQX/h9tWIPmgX8oWVT0Vb06G3lpaPh
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

