apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBRhQUR2qDI5GPvqpuAgNWpvLI+HKffqdhu6dcStUgV3/ZonZG4k17fWy9oHkbgQBG2Zwa0oIONR9ZEpZXC1fWNkJGBIKEfUuRWHWSZAVaLVEIP44CpcgB4QMfB13XUpx8YvQENmJ0wvcj+lIloGienDShPhrtx6IY8369Em0ndXRXOb1mO3Xi4i+gbwMNpNAYun73bhiFJkrxY7CXEZI7GTHjgp3wOjjpZthgVrNo+nujKJV7NAJ9MIMmhXC4sSx1Kmi4AtoT5IFyfxJB+OGboAD9Vp7LO2iX5f8UQR/ADXFG1I7YuJWgyplj89s52m5rWtPnov55ohDrtZTHXkFymvq2eb7FWfd0UPSvi80sVLxH+WDD/5fhNVG2BTkAF7lZGc8HpXNC12dFm4Ms5KGr2Kt/oE4I9LdAgJGZAvMLgXz4iwJ9Y39BD1CjhkFDaOd13JFvfROVck5odE1AJWTUr+fp7AKlqGScbC0trUVUWbiYfbjcguc//svLra3uAWjNP2eOTIQQbOi7+LHN4j/57TSaQAULRtk6aowR1iMQAN4UzAI+h/R4Z/4KOY6dTxFAPDW+WHx3iErDfO3gzPY2PF0cjJmZEQjtjXpPnEYo+WI+/ICphb3Vd2lmdwaiMx7kCT6ZRVMU6CeaYtbMpMLQqqr9+FrDNbbsIMN6szfAv79YP62CGNcUWRwdrZmeYq8rAYvD2vXhUQvfObE+mv3SyKPV1P9GnoTziXCNQBVb4xzi1ZyxQiZgO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

