apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBkIFL52BDBIAvNGeY4QbPHu7uYm+6x1LpyqRX+XH1aWJ3J6o2cFM+2NhSXWDyLmNncMW40B0nRk7jUdU1aw+Ird7pL8DTceLG6852CyMsMFVVORJAY3hTK1l1XgnbfdOAaZk2jUR2WTB5py0ZqApIg7bv9zS+KSxFcdsbC6ku4ZpEi4nfyvsl1JVvmNlzH28sGh+FDZx1i7Y/FDm3n5+REq/4YLJC9PpPHQnmF442m+tQ2mxLiGQ1Cy2TsU9e3S0rHjgQOGGFtJZnMKVjSe24fWL5ZT1nLCwa8gngEYm36z2Eu12Je+PTWIvx/AtAAa7548HPDoQ1i/aVeZhmpqLyF8Fhq5Fcpv0hV++Ry3L/pT5SEsAtzSzDOclkS8CL3eEHiRKw4AoRbnq3OLMxFIk2XNhq5KQTvXge2JmZVplP4lTqGHVEiPp1C/fNka1czfFYtmh5Z+0/fQLQUxcRGONaJcfNx8Xacha3M0lg3HOfHRWEXm65VC+QJrJdC/I5uLfJiVjtx4ohadATcLt1jm2VJJk75yTqAlzIJ/4eeJrcd7luvxktW7JO8xqUpFW2vY/TT1FI0SBFNFzEZVY0Cu8QPFilF+r1S4uy8nEQK8IfERD9h0HCBUi2/fEkFK63b3L/yTllvH5bVeFQpnzVrl8JK98ckwjfCMXWaMdjjyIrEQTh0xPZYFrpTvHfshrpr13pKCXtXth+KPmThafhfeLJ2BCoXOSLjgeS8yQ61FMZ3tDIUP1KA5kDn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

