apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBMJjs0MfDc6rP4VO/uFbQbraDxrcrMAeUfbGP0oc1c152S2HJcP2joM21uZb/NLPl0eQDnkmRaqPWfZd6rsW/BWSzCpPlTZmHATeYI9IC6h1Wii8rvbq6aqFVjjZxhpuomZV4xg2rkc0K4Vo7vkvS9pHxZgbTMEtsETA7J9lKkLM5rU7HOHwXAQOC4M4QZzbhiwlYqjSuHDUcvzMdgAD7Eo4G2ziRXHDtOb3Fb8pvrmAX3t/aNvtuv/vbrhONZz/kWLSgFul4hi6Y209BK628tYqgYyC8BIC9IpwOX9GX6Wd4FSS1XfpRhuwIHc41TjfhA18arVldAw0gCjfNA5/22MtgfhuqPu+KgCwQlxKEma+HWOF2RwfgMmc7tEf8bPH12dXeVW3fHZX3eJF70DwbUJJibKClp7CuSeikV+jKarRRYloIRCLBRlcdT3J7MPhljhZOQWXBvQuO0ZInVVg/1Mv0kEpJTOHnGOoNq1k3BWOkQX8vGeyAOcEN5eanv0Y+fw3HC+yAtU6lBQW5qHFmI/Cztp92HDXpS+dHVm52Dd6eiOm3atKJ1vaMa1Ne/fHiCVU2isjeo68bb27m9lQrxT780YH4TPDApVP+JjH9fpZRLlD1vmfpBtV4E4eLBVvDe0wpOeja6hw1cAAlv2SsNW6WeC5m+vpXh1WQK73U+2HQa85/UtjCGqg8tvDMJeG7x9UAjgAH0m7kvpwS1GFSQgtsLZjudCnbOfhxQ7VyBQ0bbi5vpP3R6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

