apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCQRQRR49yf7QMpONzL2WHMmBTJM0fg22qE2bf5mhlWUQacXsHO2MPV1l2+xaDgpMVNp81ik9RFdKEn3yS/FEBYWHyG5ObpbbvAUwQ/TknA35u3yBcg7+uT8eIlE1obONWG9QzQqF528uu/JJWSpkwIRu5cxZKD7/I0PLgBIreCBUtL69JlWjOwudZ3Px1yeMlecRHOsvl4Ifq7jFUJlWAvk4ksdq2g+01KHsKGSM4EVF8GHsA/MsmhvAdzJ7PX+AFlzG0zePyI4tel4/Euoxk0Aab9c4QvnXaflkYle2nFbrOawSO3NZYcAOMopnMgvLFTSAtkz+B+wXcGMdcK5Zq1C6u4E+X3SiiLv5fr5jnWXweWB1zI4y7w4DqlWrp1asVN08KJc2fHyEEt2bjpTupPVEUV99uw6Uy7nlpcUdOvrpkhU7YkY21nPZKA9QHAgZw1B8pZu7QTGWVG7rikNVQ55eoIa1tcM2QPVlABYTE+uD0vU0dMOq5OLzu4q42exYA/Ulz3GbQLMQSp35XnRooXAYpt8xkSJONSNZVSBqvjNBsicAt/b5WaJwSOqP3OxDx2Gokm32KoQ+9O+9/mBmDChJuHW5TfES5WFhQA7NcA08Zw5UH8PKZIRAxeCjV8oebmUT9HrpACe/WGJSHpm5pc4GCP8Nf2QxH5e63p161hII8N3mGWMFQrdIUkMC3vccbWYmiUkYy9tC2QOajkF+9P2a9ITKI3eSXSq3OMFnHFww90AgeLmLoW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

