apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBQpZUgw2XvUvAcp1A3j6heM8VC7tES051jYjCo0FiDkYCiRxu2GOiZEg7rsTyWs4X9yJzXP/fysMfljDF0GiCFxBDULzxuNujg/qpfLYgt1DOiTcMmIx7uRBVhhmMJ5l4rvwnjJ1jzgPvGfj1sfiOoJ+hKT6p+Kthk4Wa45+JdrmSkapUsflAbJyfh5WP/a6BVovsxudAubYR6w5gcivOdcOcOry4wUCD0JHTnpPqBIqKPOiyfO5jobWWmobsnUYJ2+9VLYjyOR7cfyHC4O08WYYu+27w8TLO+zoC0BmpwZdQxYvs3iIeY9MFVBhyQq0VkMGJ68cK5GTq4HmdtH9VgiNZEC0UbNYWKEHkf/0Hh4uxSPqttvNq00lrRLvfv3ZgS70SOKuDJ1XN95JLskVqXuYL657vz603vO3llpzkAfujThkEUwuiLPfAkOKocphFVoN/esXkrBZQnTHwgDXU5iiiLfHlhD72WUxbtW9gjtM02958cSlQ3hVMQp67O/iaLbW0fOBAIl5JTRjocTUHv1lrofsP+VsBOxoDyjfMj3lpyBnnTTT0DY38bwjmNDNKy8Ww3AwDgIXAV7pzGdx36lqr7C1q9k06+btDJjhCsAwI8xy+W4DrSHR4RqdnAFRGJh7/NIt/Rm3oqHWjAToHp6UtzfxMjrlIzhlmVRwhfQPi7GzrjSbLRDnSfcRhgxNqLHHwTOCFmtCRMRWyu0NT/OBa5nuKcIb+kAYd+lXpurrXaOkblwY88
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

